# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
        exclude: ".*\\.ipynb$"
      # Run the formatter
      - id: ruff-format
        exclude: ".*\\.ipynb$"
