# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Collector case population compiler."""

from collector.planner.compatibility import (
    DEFAULT_MANIFEST_ROOT,
    check_protected_coverage,
    protected_manifest_path,
)
from collector.planner.compiler import compile_population, populate
from collector.planner.context import (
    CaseCatalog,
    activate_case_catalog,
    active_case_catalog,
    active_model_path,
    get_active_case_catalog,
    get_active_model_path,
    use_case_catalog,
)
from collector.planner.coverage import (
    COVERAGE_CANONICAL_VERSION,
    CoverageDiff,
    CoverageHeader,
    CoverageManifest,
    CoverageManifestError,
    CoverageMismatchError,
    assert_legacy_subset,
    diff_coverage_manifests,
    load_coverage_manifest,
    write_coverage_manifest,
)
from collector.planner.models import (
    CaseDecision,
    DecisionKind,
    InvocationKey,
    LogicalCandidate,
    PlanContext,
    PlannedCase,
    PopulationConflictError,
    PopulationReport,
    PopulationResult,
    PopulationRule,
    RuleSource,
    canonical_json,
    canonicalize,
    legacy_rule,
)
from collector.planner.physical_keys import (
    PHYSICAL_KEY_REGISTRY,
    PHYSICAL_KEY_SCHEMA_VERSION,
    PhysicalKeyError,
    PhysicalKeySchema,
    PhysicalRowKey,
    physical_row_key,
)
from collector.planner.registry import (
    LegacyPassthroughSchema,
    OpCaseSchema,
    clear_schemas,
    get_schema,
    legacy_passthrough,
    register_schema,
    unregister_schema,
)

__all__ = [
    "COVERAGE_CANONICAL_VERSION",
    "DEFAULT_MANIFEST_ROOT",
    "PHYSICAL_KEY_REGISTRY",
    "PHYSICAL_KEY_SCHEMA_VERSION",
    "CaseCatalog",
    "CaseDecision",
    "CoverageDiff",
    "CoverageHeader",
    "CoverageManifest",
    "CoverageManifestError",
    "CoverageMismatchError",
    "DecisionKind",
    "InvocationKey",
    "LegacyPassthroughSchema",
    "LogicalCandidate",
    "OpCaseSchema",
    "PhysicalKeyError",
    "PhysicalKeySchema",
    "PhysicalRowKey",
    "PlanContext",
    "PlannedCase",
    "PopulationConflictError",
    "PopulationReport",
    "PopulationResult",
    "PopulationRule",
    "RuleSource",
    "activate_case_catalog",
    "active_case_catalog",
    "active_model_path",
    "assert_legacy_subset",
    "canonical_json",
    "canonicalize",
    "check_protected_coverage",
    "clear_schemas",
    "compile_population",
    "diff_coverage_manifests",
    "get_active_case_catalog",
    "get_active_model_path",
    "get_schema",
    "legacy_passthrough",
    "legacy_rule",
    "load_coverage_manifest",
    "physical_row_key",
    "populate",
    "protected_manifest_path",
    "register_schema",
    "unregister_schema",
    "use_case_catalog",
    "write_coverage_manifest",
]
